# Generated by Django 4.2.6 on 2023-10-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
