# Generated by Django 4.2.6 on 2023-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_user_alter_message_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
