# Generated by Django 4.2.6 on 2023-10-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
